// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjChatBot.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public string Option { get; set; }

    public string OtherReason { get; set; }

    public DateTime? CreatedAt { get; set; }
}