// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjChatBot.Models;

public partial class Menu
{
    public int Id { get; set; }

    public string ImagePath { get; set; }

    public string TextContent { get; set; }

    public DateTime? CreatedAt { get; set; }
}