// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjChatBot.Models;

public partial class PieChartDatum
{
    public int Id { get; set; }

    public string Type { get; set; }

    public string Reason { get; set; }

    public int? Count { get; set; }
}