// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjChatBot.Models;

public partial class ProductCard
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string ImageFileName { get; set; }

    public string Name1 { get; set; }

    public string Url1 { get; set; }

    public string Name2 { get; set; }

    public string Url2 { get; set; }
}