// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace prjChatBot.Models;

public partial class ProductCard
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string ImageFileName { get; set; }

    [RegularExpression(@"^(http|https)://.*", ErrorMessage = "Please enter a valid URL starting with http or https.")]
    public string ProductInfoUrl { get; set; }

    [RegularExpression(@"^(http|https)://.*", ErrorMessage = "Please enter a valid URL starting with http or https.")]
    public string PurchaseUrl { get; set; }
}